`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 05.03.2026 16:12:25
// Design Name: 
// Module Name: SPI_Protocol
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


// SPI Master Module
// Responsible for generating SPI clock, sending data on MOSI
// and receiving data on MISO using full-duplex communication

module SPI_Master(

    input clk,                // System clock (main clock of FPGA/ASIC)
    input rst,                // Active high reset signal
    input tx_enable,          // Signal to start SPI transmission
    input miso,               // Master Input Slave Output (data from slave)

    input [7:0] tx_data,      // 8-bit data to transmit from master

    output reg mosi,          // Master Output Slave Input (data to slave)
    output reg cs,            // Chip Select (active low) to enable slave
    output reg sclk,          // SPI serial clock generated by master
    output reg [7:0] rx_data, // Data received from slave

    output reg done           // Indicates transmission complete
);


// FSM state 
parameter IDLE     = 2'b00;   // Waiting state
parameter LOAD     = 2'b01;   // Load transmit data
parameter TRANSFER = 2'b10;   // Shift data between master and slave
parameter FINISH   = 2'b11;   // Transmission complete


reg [1:0] state;              // Current state of FSM

reg [2:0] bit_count;          // Counts number of bits transmitted (8-bit transfer)

reg [7:0] shift_tx;           // Shift register used to send data serially on MOSI
reg [7:0] shift_rx;           // Shift register used to store received MISO data

reg [2:0] clk_div;            // Clock divider counter for generating SPI clock


// ---------------------------------------------------------
// Clock Divider Logic
// Generates slower SPI clock (sclk) from system clock
// ---------------------------------------------------------

always @(posedge clk or posedge rst)
begin
    if(rst)
    begin
        clk_div <= 0;         // Reset clock divider
        sclk <= 0;            // Reset SPI clock
    end

    // Clock divider active only during data transfer
    else if(state == TRANSFER)
    begin
        if(clk_div == 3)      // Divide system clock by 8
        begin
            clk_div <= 0;
            sclk <= ~sclk;    // Toggle SPI clock
        end
        else
            clk_div <= clk_div + 1;
    end

    else
    begin
        clk_div <= 0;
        sclk <= 0;
    end
end



// ---------------------------------------------------------
// SPI Master Finite State Machine (FSM)
// Controls data loading, shifting, and completion
// ---------------------------------------------------------

always @(posedge clk or posedge rst)
begin
    if(rst)
    begin
        state <= IDLE;        // Reset FSM to IDLE state
        cs <= 1;              // Disable slave (chip select inactive)
        mosi <= 0;            // Clear MOSI line
        done <= 0;            // Clear done flag
        bit_count <= 0;       // Reset bit counter
        shift_tx <= 0;        // Clear transmit shift register
        shift_rx <= 0;        // Clear receive shift register
        rx_data <= 0;         // Clear received data register
    end

    else
    begin
        case(state)


        // -------------------------------------------------
        // IDLE State
        // Wait for transmission enable signal
        // -------------------------------------------------

        IDLE:
        begin
            done <= 0;        // Transfer not finished
            cs <= 1;          // Slave disabled

            if(tx_enable)     // Start transmission
                state <= LOAD;
        end


        // -------------------------------------------------
        // LOAD State
        // Load transmit data into shift register
        // -------------------------------------------------

        LOAD:
        begin
            cs <= 0;               // Enable slave device
            shift_tx <= tx_data;   // Load data to transmit
            shift_rx <= 0;         // Clear receive shift register

            bit_count <= 3'd7;     // 8-bit transfer counter
            state <= TRANSFER;     // Move to data transfer state
        end



        // -------------------------------------------------
        // TRANSFER State
        // Perform SPI data shifting
        // -------------------------------------------------

        TRANSFER:
        begin
            if(clk_div == 3)
            begin
                sclk <= ~sclk;     // Toggle SPI clock
                clk_div <= 0;

                // SPI Mode-0 Timing
                // Falling edge → transmit MOSI
                if(sclk == 0)
                begin
                    mosi <= shift_tx[7];               // Send MSB bit
                    shift_tx <= {shift_tx[6:0],1'b0};  // Shift left
                end

                // Rising edge → receive MISO
                else
                begin
                    shift_rx <= {shift_rx[6:0], miso}; // Shift received bit

                    if(bit_count == 0)
                        state <= FINISH;               // All bits transferred
                    else
                        bit_count <= bit_count - 1;    // Decrement counter
                end
            end
            else
                clk_div <= clk_div + 1;
        end



        // -------------------------------------------------
        // FINISH State
        // Transmission completed
        // -------------------------------------------------

        FINISH:
        begin
            cs <= 1;               // Disable slave
            done <= 1;             // Indicate transfer complete

            rx_data <= shift_rx;   // Store received data

            state <= IDLE;         // Return to IDLE state
        end


        endcase
    end
end

endmodule

// SPI Slave module
// This module receives data from the SPI master through MOSI
// and simultaneously sends data back to the master through MISO.
// Communication is controlled using SCLK and CS signals.

module SPI_Slave(

    input sclk,          // SPI clock generated by master
    input cs,            // Chip select signal from master (active low)
    input mosi,          // Data sent from master to slave
    output reg miso,     // Data sent from slave back to master
    input [7:0] tx_data, // 8-bit data that slave wants to transmit
    output reg [7:0] rx_data // 8-bit data received from master
);

// Shift register used for transmitting data bit-by-bit on MISO
reg [7:0] shift_tx;

// Shift register used to collect incoming bits from MOSI
reg [7:0] shift_rx;


// ------------------------------------------------------------------
// Initial block
// Used only in simulation to initialize registers
// ------------------------------------------------------------------
initial begin
shift_tx = 0;   // Clear transmit shift register
shift_rx = 0;   // Clear receive shift register
miso = 0;       // Default output value on MISO
end


// ------------------------------------------------------------------
// When CS goes low (slave selected by master)
// Load transmit data into shift register
// Also place the first bit on MISO so master can read it
// ------------------------------------------------------------------
always @(negedge cs)
begin
    shift_tx <= tx_data;     // Load slave transmit data
    miso <= tx_data[7];      // Send MSB first on MISO
end


// ------------------------------------------------------------------
// On rising edge of SCLK
// Slave samples incoming data from MOSI
// This follows SPI Mode-0 timing (sample on rising edge)
// ------------------------------------------------------------------
always @(posedge sclk)
begin
    if(!cs) // Only receive data when slave is selected
        shift_rx <= {shift_rx[6:0], mosi}; // Shift incoming bit into register
end


// ------------------------------------------------------------------
// On falling edge of SCLK
// Slave prepares the next bit to send on MISO
// ------------------------------------------------------------------
always @(negedge sclk)
begin
    if(!cs)
    begin
        shift_tx <= {shift_tx[6:0],1'b0}; // Shift transmit register
        miso <= shift_tx[6];              // Output next bit on MISO
    end
end


// ------------------------------------------------------------------
// When CS goes high again
// The SPI transfer is finished
// Store the received byte into rx_data
// ------------------------------------------------------------------
always @(posedge cs)
begin
    rx_data <= shift_rx; // Final received data from master
end

endmodule

// Top-level SPI module
// This module connects the SPI Master and SPI Slave together.
// It acts like a small system where the master communicates with the slave.

module SPI_Top(

    input clk,             // System clock used by SPI master
    input rst,             // Reset signal
    input tx_enable,       // Signal used to start SPI transfer
    input [7:0] master_tx,   // data from testbench to master
    input [7:0] slave_tx,    // data from testbench to slave
    output [7:0] slave_rx, // Data received by slave from master
    output [7:0] master_rx,// Data received by master from slave
    output done            // Indicates that SPI transfer is complete

);

// Internal wires used to connect master and slave signals
wire mosi;  // Master Out Slave In data line
wire miso;  // Master In Slave Out data line
wire cs;    // Chip select signal from master
wire sclk;  // SPI clock generated by master


// ------------------------------------------------------------------
// SPI Master Instance
// This module generates the SPI clock and controls communication.
// It sends data to the slave through MOSI and receives data via MISO.
// ------------------------------------------------------------------
SPI_Master master(

    .clk(clk),            // System clock input
    .rst(rst),            // Reset signal
    .tx_enable(tx_enable),// Start SPI transfer
    .miso(miso),          // Data coming from slave
//    .tx_data(8'hFE),      // Example data sent from master (FE)
    .tx_data(master_tx),   // data comes from testbench
    .mosi(mosi),          // Data sent to slave
    .cs(cs),              // Chip select signal
    .sclk(sclk),          // SPI clock output
    .rx_data(master_rx),  // Data received from slave
    .done(done)           // Transfer completion signal

);


// ------------------------------------------------------------------
// SPI Slave Instance
// This module receives MOSI data from the master and
// sends its own data back through MISO.
// ------------------------------------------------------------------
SPI_Slave slave(

    .sclk(sclk),         // SPI clock from master
    .cs(cs),             // Chip select from master
    .mosi(mosi),         // Data from master
    .miso(miso),         // Data sent back to master
   // .tx_data(8'hA5),     // Example data sent by slave (A5)
     .tx_data(slave_tx),   // data comes from testbench
    .rx_data(slave_rx)   // Data received from master

);

endmodule
